
version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: train_booking_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/prisma/init-extensions.sql:/docker-entrypoint-initdb.d/init-extensions.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: train_booking_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: train_booking_backend
    env_file:
      - .env
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    entrypoint: []
    command: npm run dev
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      prometheus:
        condition: service_started
      tempo:
        condition: service_started
      loki:
        condition: service_started

  frontend:
    image: node:20-alpine
    container_name: train_booking_frontend
    environment:
      NODE_ENV: development
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    entrypoint: []
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus:latest
    container_name: train_booking_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: train_booking_grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      GF_DASHBOARDS_JSON_ENABLED: "true"
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:3.5.0
    container_name: train_booking_loki
    ports:
      - "3100:3100"
    command:
      - -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-local-config.yaml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki

  tempo:
    image: grafana/tempo:latest
    container_name: train_booking_tempo
    ports:
      - "4318:4318"
    command:
      - -config.file=/etc/tempo/local-config.yaml
    volumes:
      - ./tempo-local-config.yaml:/etc/tempo/local-config.yaml:ro

volumes:
  pgdata:
  redisdata:
  grafana_data:
  loki_data:
